name: Build Release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: bash scripts/build.sh

    - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          draft: true
          files: |
            build/rrc*
          body: |
            ## ChangeLog
            * idk